# Generated by Django 6.0.2 on 2026-02-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contact',
            new_name='CheckIn',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cpassword',
            new_name='CheckOut',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='firstname',
            new_name='aadharno',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='lastname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='password',
            new_name='num',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
