# Generated by Django 6.0.2 on 2026-02-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_client_city_client_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='people',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
